### ISSUE TITLE
Some players can't log in

### ISSUE THREAD

**Issue by SometimesRain** [SometimesRain/crazyclient#8]
Probably a simple null value exception. I can't fix it by myself.

**Comment by BurgerLoverMx** [comment]
Might just be a problem with RotMG cause I can't sign in to one of my accounts anymore and when I try to send an email to reset the password then I just never recieve it :/

**Comment by SometimesRain** [comment]
I've had way too many people telling me this is happening and it's just my client as well. When they play on the official client they can login just fine.

The issue is real.

**Comment by SometimesRain** [comment]
Fixed in 9.5
